/****** Object:  Table [dbo].[TrackArtist]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TrackArtist](
	[Id] [uniqueidentifier] NOT NULL,
	[TrackId] [uniqueidentifier] NOT NULL,
	[ArtistId] [uniqueidentifier] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[LastUpdatedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_TrackArtist] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_TrackArtist_ArtistId] ON [dbo].[TrackArtist]
(
	[ArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_TrackArtist_TrackId] ON [dbo].[TrackArtist]
(
	[TrackId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_TrackArtist_TrackId_ArtistId] ON [dbo].[TrackArtist]
(
	[TrackId] ASC,
	[ArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[TrackArtist] ADD  CONSTRAINT [DF_TrackArtist_Id]  DEFAULT (newsequentialid()) FOR [Id]
ALTER TABLE [dbo].[TrackArtist]  WITH CHECK ADD  CONSTRAINT [FK_TrackArtist_Artist] FOREIGN KEY([ArtistId])
REFERENCES [dbo].[Artist] ([Id])
ALTER TABLE [dbo].[TrackArtist] CHECK CONSTRAINT [FK_TrackArtist_Artist]
ALTER TABLE [dbo].[TrackArtist]  WITH CHECK ADD  CONSTRAINT [FK_TrackArtist_Track] FOREIGN KEY([TrackId])
REFERENCES [dbo].[Track] ([Id])
ALTER TABLE [dbo].[TrackArtist] CHECK CONSTRAINT [FK_TrackArtist_Track]